#!/bin/bash

VERSION=latest
IMAGE="henrikgeissler/fullstackfun:$VERSION"

#printenv SSH_PW | ssh root@104.248.251.75 "docker pull $IMAGE && docker tag $IMAGE dokku/api:$VERSION && dokku tags:deploy api $VERSION"
